services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ci4-web
    ports:
      - "8090:80"
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    depends_on: [db]
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: ci4-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: appdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
      TZ: Asia/Dili
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

  pma:
    image: phpmyadmin:5
    container_name: ci4-pma
    environment:
      PMA_HOST: db
      UPLOAD_LIMIT: 256M
      TZ: Asia/Dili
    ports:
      - "8091:80"
    depends_on: [db]
    restart: unless-stopped

volumes:
  db_data:
